apiVersion: v1
kind: Service
metadata:
  labels:
    app: poornima-express-sample-app
    app.kubernetes.io/instance: poornima-express-sample-app
    app.kubernetes.io/name: poornima-express-sample-app
  name: poornima-express-sample-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: poornima-express-sample-app
    app.kubernetes.io/name: poornima-express-sample-app
  sessionAffinity: None
  type: ClusterIP